### ISSUE TITLE
Make Tshield compatible with Windows SO

### ISSUE THREAD

**Issue by flaviomeira** [diegorubin/tshield#61]
In order to make Tshield compatible with Windows, Tshield cannot create folders and files with '?' (question mark) character in the name.
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

Expected: Tshield get the windows compatibility flag from config file and replace '?' for '%3f' (%3f is the ascii for '?' in Windows-1252 charset).

**Comment by diegorubin** [comment]
release 0.12.0.0
